ALTER TABLE provider_credentials
    ALTER COLUMN created_at DROP DEFAULT,
    ALTER COLUMN updated_at DROP DEFAULT,
    ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE
        USING (created_at AT TIME ZONE 'UTC'),
    ALTER COLUMN updated_at TYPE TIMESTAMP WITHOUT TIME ZONE
        USING (updated_at AT TIME ZONE 'UTC'),
    ALTER COLUMN created_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    ALTER COLUMN updated_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC');

ALTER TABLE models
    ALTER COLUMN created_at DROP DEFAULT,
    ALTER COLUMN updated_at DROP DEFAULT,
    ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE
        USING (created_at AT TIME ZONE 'UTC'),
    ALTER COLUMN updated_at TYPE TIMESTAMP WITHOUT TIME ZONE
        USING (updated_at AT TIME ZONE 'UTC'),
    ALTER COLUMN created_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    ALTER COLUMN updated_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC');

ALTER TABLE sessions
    ALTER COLUMN created_at DROP DEFAULT,
    ALTER COLUMN updated_at DROP DEFAULT,
    ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE
        USING (created_at AT TIME ZONE 'UTC'),
    ALTER COLUMN updated_at TYPE TIMESTAMP WITHOUT TIME ZONE
        USING (updated_at AT TIME ZONE 'UTC'),
    ALTER COLUMN last_turn_at TYPE TIMESTAMP WITHOUT TIME ZONE
        USING (last_turn_at AT TIME ZONE 'UTC'),
    ALTER COLUMN created_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    ALTER COLUMN updated_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC');

ALTER TABLE turns
    ALTER COLUMN started_at DROP DEFAULT,
    ALTER COLUMN updated_at DROP DEFAULT,
    ALTER COLUMN started_at TYPE TIMESTAMP WITHOUT TIME ZONE
        USING (started_at AT TIME ZONE 'UTC'),
    ALTER COLUMN ended_at TYPE TIMESTAMP WITHOUT TIME ZONE
        USING (ended_at AT TIME ZONE 'UTC'),
    ALTER COLUMN updated_at TYPE TIMESTAMP WITHOUT TIME ZONE
        USING (updated_at AT TIME ZONE 'UTC'),
    ALTER COLUMN started_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    ALTER COLUMN updated_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC');

ALTER TABLE messages
    ALTER COLUMN created_at DROP DEFAULT,
    ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE
        USING (created_at AT TIME ZONE 'UTC'),
    ALTER COLUMN created_at SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC');

ALTER TABLE trace_spans
    ALTER COLUMN started_at TYPE TIMESTAMP WITHOUT TIME ZONE
        USING (started_at AT TIME ZONE 'UTC'),
    ALTER COLUMN ended_at TYPE TIMESTAMP WITHOUT TIME ZONE
        USING (ended_at AT TIME ZONE 'UTC');
