import { describe, expect, it } from "vitest";
import { checkCommitMessage } from "./commit-msg";

describe("checkCommitMessage", () => {
  it("accepts a subject with or without a scope, followed by a body after a blank line", () => {
    expect(
      checkCommitMessage("feat(computer): crew 命令：经 stdin 在房间里回复\n\n- shim：从 stdin 读取正文。\n"),
    ).toEqual([]);
    expect(checkCommitMessage("test: 规范测试流程\n")).toEqual([]);
  });

  it("ignores git comment lines and trailing blank lines", () => {
    expect(checkCommitMessage("docs: 更新测试规范\n\n# Please enter the commit message\n\n")).toEqual([]);
  });

  it("rejects an unknown type or a missing colon", () => {
    expect(checkCommitMessage("feature: 新增界面")).toHaveLength(1);
    expect(checkCommitMessage("feat 新增界面")).toHaveLength(1);
  });

  it("rejects a description written without Chinese", () => {
    expect(checkCommitMessage("fix(server): handle missing room")).toEqual(["标题的描述用中文写"]);
  });

  it("rejects a body that starts right after the subject", () => {
    expect(checkCommitMessage("fix: 修复重连\n- 中止时取消读取")).toEqual(["标题与正文之间空一行"]);
  });

  it("leaves messages generated by git alone", () => {
    expect(checkCommitMessage("Merge branch 'dev' into refactor")).toEqual([]);
    expect(checkCommitMessage("fixup! fix: 修复重连")).toEqual([]);
  });
});
